apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: simple-nodejs-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: kbriones/simple-nodejs-app
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
